[package]
name = "runner"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
getopts = "*"
aoc = { path = "../aoc" }
day1 = { path = "../day1" }
day2 = { path = "../day2" }
day3 = { path = "../day3" }
tokio = { version = "1.41.1", features = ["full"] }
url = "2.5.4"
